services:
  web:
    image: agenda-django
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      DEBUG: "1"

  sut:
    image: agenda-django
    depends_on:
      web:
        condition: service_healthy
    command: >
      sh -c "for i in {1..10}; do curl -s http://web:8000 && exit 0 || sleep 3; done; exit 1"
