version: '3.9'

services:
  web:
    image: ${TESTING_IMAGE}
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  sut:
    image: ${TESTING_IMAGE}
    depends_on:
      web:
        condition: service_started
    command: >
      sh -c "for i in {1..10}; do curl -s http://web:8000 && exit 0 || sleep 3; done; exit 1"
