version: '3.9'

services:
  allhands22:
    image: "${TESTING_IMAGE}"
    ports:
      - "8000:8000"

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    volumes:
      - ./healthchecks:/healthchecks
    healthcheck:
      test: /healthchecks/postgres-healthcheck
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  sut:
    
    tty: true
    stdin_open: true
    image: "${TESTING_IMAGE}"
    depends_on:
      allhands22:
        condition: service_started
      postgres:
        condition: service_healthy
    command: >
      sh -c "for i in {1..10}; do curl -s http://allhands22:8000 && exit 0 || sleep 3; done; exit 1"
