version: '3.9'

services:
  web:
    image: ${TESTING_IMAGE}
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  sut:
    image: ${TESTING_IMAGE}
    depends_on:
      web:
        condition: service_started
    command: >
      sh -c "for i in {1..20}; do echo '⌛ Intento '$i; curl -s http://web:8000 && echo '✅ API disponible' && exit 0 || sleep 3; done; echo '❌ Falló el acceso a la API'; exit 1"

