apiVersion: apps/v1
kind: Deployment
metadata:
  name: apytest
  labels:
    app: apytest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apytest
  template:
    metadata:
      labels:
        app: apytest
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: apytest
          image: "ghcr.io/kuota1/apytest:${TESTING_IMAGE}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          tty: true
          stdin: true

